#define DIRECTIVE 1
#define FILEINCLUDED 2
#define INT 3
#define IDENTIFIER 4
#define LEFTBRACKET 5
#define RIGHTBRACKET 6
#define LEFTCURLYBRACKET 7
#define RIGHTCURLYBRACKET 8
#define COMMA 9
#define EQUALS 10
#define PLUS 11
#define MINUS 12
#define MULTIPLY 13
#define POWER 15
#define COLON 16
#define RETURN 17
#define NUMBER 18
